"""Added username to review

Revision ID: 661d9aa1210f
Revises: eb7b0a15468a
Create Date: 2025-01-25 13:58:12.066831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '661d9aa1210f'
down_revision = 'eb7b0a15468a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=50), nullable=False))
        batch_op.alter_column('rating',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.alter_column('rating',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('username')

    # ### end Alembic commands ###
