"""Add added_by column to Movie

Revision ID: d66b096bbfb8
Revises: 111d4d5dba50
Create Date: 2025-01-25 19:51:08.426832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd66b096bbfb8'
down_revision = '111d4d5dba50'
branch_labels = None
depends_on = None


def upgrade():
    # ### Step 1: Spalte mit NULL erlauben ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('added_by', sa.Integer(), nullable=True))  # Erst NULL erlauben
        batch_op.create_foreign_key(None, 'user', ['added_by'], ['id'])

    # ### Step 2: Bestehende Einträge mit Default-User updaten ###
    op.execute("UPDATE movie SET added_by = 1 WHERE added_by IS NULL")  # Setze z. B. auf Admin-User (ID=1)

    # ### Step 3: Jetzt `added_by` auf NOT NULL setzen ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.alter_column('added_by', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('added_by')

    # ### end Alembic commands ###
